apiVersion: v2
type: application
name: scribe
description: |
  Scribe is a tool that automates the propagation of annotations across Kubernetes resources based
  on the annotations in a Namespace.
home: https://github.com/anza-labs/scribe
version: 0.3.3
appVersion: "v0.3.0"
keywords: []
annotations: {}
maintainers:
  - name: Mateusz Urbanek
    email: matueusz.urbanek.98@gmail.com
    url: http://linkedin.com/in/urbanekmateusz
