apiVersion: v1
kind: Service
metadata:
  name: {{ include "glauth.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glauth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports: [] # TODO
  selector:
    {{- include "glauth.selectorLabels" . | nindent 4 }}
